# -*- coding: utf-8 -*-
"""DawerStivenPatino3Modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQbBtFu9IreRzYgw5RWqVRaQvmX8wsaA
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

data=pd.read_excel("/content/Salary.xlsx")
data.head()

data.columns
X=data["YearsExperience"]
Y=data["Salary"]
model=LinearRegression()
model.fit(X.values.reshape(-1,1),Y)
y_pred=model.predict(X.values.reshape(-1,1))
r2=r2_score(Y,y_pred)

plt.figure(figsize=[10,6])
plt.scatter(X,Y, color="yellow",label="Datos Reales")
plt.plot(X,y_pred,color="Blue",linewidth=2,label="Regresion lineal")
plt.xlabel("Años de experiencia")
plt.ylabel("Salario")
plt.title("Años de experiencia vs Salario")
plt.legend()
plt.grid(True)
plt.show()

print(f"Ecuación de la recta: y= {model.coef_[0]:.2f}x+ {model.intercept_:2f}")
print(f"Coeficiente de Determinación: {r2:.2f}")

data2=pd.read_csv("/content/dataset_edad_precio_seguro.csv")
data2.head()

data2.columns

X=data2["Edad"]
Y=data2["PrecioSeguro"]
model2=LinearRegression()
model2.fit(X.values.reshape(-1,1),Y)
y_pred2=model2.predict(X.values.reshape(-1,1))
r2_seguro=r2_score(Y,y_pred)

plt.figure(figsize=[10,6])
plt.scatter(X,Y, color="red",label="Datos Reales")
plt.plot(X,y_pred2,color="Blue",linewidth=2,label="Regresion lineal")
plt.xlabel("Edad")
plt.ylabel("PrecioSeguro")
plt.title("Precio del seguro")
plt.legend()
plt.grid(True)
plt.show()

print(f"Ecuación de la recta: y= {model2.coef_[0]:.2f}x+ {model2.intercept_:2f}")
print(f"Coeficiente de Determinación: {r2_seguro:.2f}")

data3=pd.read_csv("/content/house_prices_large.csv")
data3.head()

data3.columns

X=data3["House_Size"]
Y=data3["Price"]
model3=LinearRegression()
model3.fit(X.values.reshape(-1,1),Y)
y_pred3=model3.predict(X.values.reshape(-1,1))
r2_pvz=r2_score(Y,y_pred3)

plt.figure(figsize=[10,6])
plt.scatter(X,Y, color="red",label="Datos Reales")
plt.plot(X,y_pred3,color="Blue",linewidth=2,label="Regresion lineal")
plt.xlabel("House_Prize")
plt.ylabel("Price")
plt.title("Precio de la casa")
plt.legend()
plt.grid(True)
plt.show()

print(f"Ecuación de la recta: y= {model3.coef_[0]:.2f}x+ {model3.intercept_:2f}")
print(f"Coeficiente de Determinación: {r2_pvz:.2f}")